apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: exam-rodrigosousa-august
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3d-k3s-default-agent-1
      containers:
      - name: backend
        image: rsousa24/big_data_and_ai-24_august_backend:version1 
        ports:
        - containerPort: 80
        env:
        - name: NAME
          value: "Rodrigo"  
        - name: DATE
          value: "2024-08-29"  

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: exam-rodrigosousa-august
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30011  # Exposing service on NodePort 30011
  type: NodePort
