apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: exam-rodrigosousa-august
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rsousa22/big_data_and_ai-24_august_frontend:version1
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: exam-rodrigosousa-august
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30010  # NodePort for frontend
