services:
  backend:
    image: rsousa24/big_data_and_ai-24_august_backend:version1
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - 8001:80
  frontend:
    image: rsousa24/big_data_and_ai-24_august_frontend:version1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    environment:
      API_PORT: 80
      API_HOST: backend
      NAME: "Rodrigo"
