services:
  web:
    build: 
      context: ./pointsAPP
    ports:
      - "5000:5000"
    networks:
      - web_network
      - db_network
    depends_on:
      db:
        condition: service_healthy  
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_DB=points
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=examen
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "student", "-d", "points"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  web_network:
  db_network:

volumes:
  db_data:
